version: "2.2"

services:
  spring-petclinic:
    build: ./
    ports:
      - "8020:8080"
    environment:
      - DB=--spring.profiles.active=postgres
    env_file:
      - .env
  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    env_file:
      - .env
